AutoStore/AutoStore/Models/NHASANXUAT.cs
namespace AutoStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("NHASANXUAT")]
    public partial class NHASANXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHASANXUAT()
        {
            SANPHAMs = new HashSet<SANPHAM>();
        }

        [Key]
        [StringLength(10)]
        public string MANSX { get; set; }

        [StringLength(50)]
        public string TENNSX { get; set; }

        [StringLength(20)]
        public string DIENTHOAI { get; set; }

        [StringLength(50)]
        public string MOTA { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}

AutoStore/AutoStore/Controllers/System/NhaSanXuatController.cs
using AutoStore.Models;
using System.Linq;
using System.Web.Mvc;

namespace AutoStore.Controllers.System
{
    [SessionTimeout]
    public class NhaSanXuatController : Controller
    {
        private DBConnection db = new DBConnection();

        public ActionResult Index()
        {
            return View(db.NHASANXUATs.ToList().OrderBy(a => a.TENNSX));
        }

        [HttpPost]
        public ActionResult Insert()
        {
            string objname = Request.Form["name"];
            string objphone = Request.Form["phone"];
            string objmota = Request.Form["mota"];
            NHASANXUAT temp = new NHASANXUAT { MANSX = FuncClass.genNextCode(), TENNSX = objname, DIENTHOAI = objphone, MOTA = objmota };
            db.NHASANXUATs.Add(temp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string ID)
        {
            var temp = new NHASANXUAT { MANSX = ID };
            db.NHASANXUATs.Attach(temp);
            db.NHASANXUATs.Remove(temp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult update(string id)
        {
            var result = db.NHASANXUATs.SingleOrDefault(a => a.MANSX == id);
            if (result != null)
            {
                result.TENNSX = Request.Form["name"];
                result.MOTA = Request.Form["mota"];
                result.DIENTHOAI = Request.Form["phone"];
                db.SaveChanges();
            }

            //if(id=="")
            //{
            //    KHACHHANG temp = new KHACHHANG { MAKH = FuncClass.genNextCode(), TENKH = ten, DIACHI = adress, DIENTHOAI = phone, EMAIL = email };
            //    db.KHACHHANGs.Add(temp);
            //    db.SaveChanges();
            //}
            return RedirectToAction("Index");
        }
    }
}

AutoStore/AutoStore/Views/NhaSanXuat/Index.cshtml
@model IEnumerable<AutoStore.Models.NHASANXUAT>


<div class="title_left">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-left top_search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
    </div>
</div>
<div class="title_right">
    <a href="#" class="pull-right" style="margin-right:5px"><i class="fa fa-chevron-right"></i> Nhà sản xuất</a>
    <a href="#" class="pull-right" style="margin-right:5px"><i class="fa fa-chevron-right"></i> Danh mục</a>
    <a href="@Url.Action("Index", null, new { area = string.Empty, controller = "Home" }, Request.Url.Scheme)" class="pull-right" style="margin-right:5px"><i class="fa fa-home"></i> Home </a>
</div>

<div class="row">


    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Nhà sản xuất<small>| Lưu trữ dữ liệu</small></h2>
                @*<button type="button" style="margin-bottom:0px;margin-right:5px" class="btn btn-primary navbar-right">Tìm kiếm</button>*@
                <button type="button" style="margin-bottom:0px;margin-right:5px" class="btn btn-primary navbar-right" data-toggle="modal" data-target="#insert">Thêm mới</button>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">

                    <div class="row">
                        <div class="col-sm-12">
                            <table id="datatable" class="table table-striped table-bordered dataTable no-footer jambo_table bulk_action" role="grid" aria-describedby="datatable_info">
                                <thead>
                                    <tr>
                                        <th style="text-align:center;width:80px">STT</th>
                                        <th>Tên nhà sản xuất<i class="fa fa-sort pull-right"></i></th>
                                        <th style="width: 350px;">Số điện thoại<i class="fa fa-sort pull-right"></i></th>
                                        <th style="width: 400px;">Mô tả<i class="fa fa-sort pull-right"></i></th>
                                        <th>Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{int count = 1; }
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td style="text-align:center">
                                                @count
                                                @{ count += 1;}
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TENNSX)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DIENTHOAI)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MOTA)
                                            </td>
                                            <td>
                                                <button type="button" style="margin-bottom:0px" class="btn btn-success btn-xs" onclick="javascript:DetailFunc(@item.MANSX,'@item.TENNSX','@item.DIENTHOAI','@item.MOTA')">Chi tiết</button>
                                                <button type="button" style="margin-bottom:0px" class="btn btn-warning btn-xs" onclick="javascript:setedit(@item.MANSX,'@item.TENNSX','@item.DIENTHOAI','@item.MOTA')">Sửa</button>
                                                <button type="button" style="margin-bottom:0px" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal" onclick="javascript:confirmDelete(@item.MANSX, '@item.TENNSX')">Xóa</button>

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*------------------INSERT---------------------*@
<div class="x_content">
    <div class="modal fade bs-example-modal-lg" id="insert" tabindex="-1" role="dialog" data-backdrop="static" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>

                    <h4 class="modal-title" id="myModalLabelinsert"><i class="fa  fa-chevron-right"></i>  Thêm mới nhà sản xuất</h4>
                </div>
                <div class="modal-body">

                </div>
                @using (Html.BeginForm("Insert", "NhaSanXuat"))
                {
                    <div class="form-horizontal form-label-left" novalidate>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                                Tên nhà sản xuất <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" name="name" placeholder="Honda,Ducati..." required="required" type="text">
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telephone">
                                Số điện thoại <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="tel" id="phone" name="phone" placeholder="09********* etc..." required="required" data-validate-length-range="8,20" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                                Mô tả <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="textarea" placeholder="mô tả..." required="required" name="mota" class="form-control col-md-7 col-xs-12"></textarea>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" onclick="emptyvalue()" class="btn btn-default" data-dismiss="modal">Bỏ qua</button>
                            <button id="send" type="submit" class="btn btn-primary">Lưu trữ</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@*--------------------------------------EDIT---------------------------------*@
<div class="x_content">
    <div class="modal fade bs-example-modal-lg" id="edit" tabindex="-1" role="dialog" data-backdrop="static" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>

                    <h4 class="modal-title" id="myModalLabelinsert"><i class="fa  fa-chevron-right"></i>  Sửa đổi dữ liệu</h4>
                </div>
                <div class="modal-body">

                </div>
                @using (Html.BeginForm("update", "NhaSanXuat", new { idnsx = "6" }, FormMethod.Post, new { @id = "formupdate" }))
                {
                <div class="form-horizontal form-label-left" novalidate>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                            Tên nhà sản xuất <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="nameedit" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" name="name" placeholder="Honda,Ducati..." required="required" type="text">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telephone">
                            Số điện thoại <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="tel" id="phoneedit" name="phone" placeholder="09********* etc..." required="required" data-validate-length-range="8,20" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            Mô tả <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="textareaedit" placeholder="mô tả..." required="required" name="mota" class="form-control col-md-7 col-xs-12"></textarea>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" onclick="emptyvalue()" class="btn btn-default" data-dismiss="modal">Bỏ qua</button>
                        <button id="send1" type="submit" class="btn btn-primary">Lưu trữ</button>
                    </div>
                </div>
                }

            </div>
        </div>
    </div>
</div>


@*--------Modal confirm delete--------------*@
<div class="x_content">
    <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" data-backdrop="static" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>

                    <h4 class="modal-title" id="myModalLabel"><i class="fa  fa-chevron-right"></i>  Xác nhận xóa nhà sản xuất</h4>
                </div>
                <div class="modal-body">
                    <h4>Bạn có chắc chắn muốn xóa nhà sản xuất <code id="lable"></code> ?</h4>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Bỏ qua</button>
                    <button id="btnContinueDelete" type="submit" class="btn btn-danger">Xóa</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Content/vendors/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">


    function confirmDelete(id, ten) {
        $('#lable').html(ten);
        $("#btnContinueDelete").click(function () {
            $.ajax({
                url: "/NhaSanXuat/Delete",
                data: { 'Id': id },
                datatype: 'html',
                type: 'Get',
                success: function () {
                    console.log("xoa thanh cong");
                    location.reload();
                },
                error: function () {
                }
            });
        });
    }




    function setedit(id, ten, phone, mota) {
        $('#edit').modal('toggle');
        $('#nameedit').val(ten);
        $('#phoneedit').val(phone);
        $('#textareaedit').val(mota);
        $('#formupdate').attr("action", "/NhaSanXuat/update?id=" + id);
    }





    function DetailFunc(id, ten, phone, mota) {
        $('#insert').modal('toggle');
        $('#myModalLabelinsert').html('<i class="fa  fa-chevron-right"></i>     Chi tiết nhà cung cấp');
        $('#name').val(ten);
        $('#phone').val(phone);
        $('#textarea').val(mota);
        $("#name").prop('disabled', true);
        $("#phone").prop('disabled', true);
        $("#textarea").prop('disabled', true);
        $("#send").prop('disabled', true);
    }


    function emptyvalue() {
        $('#name').val('');
        $('#phone').val('');
        $('#textarea').val('');
        $("#send").prop('disabled', false);
        $("#name").prop('disabled', false);
        $("#phone").prop('disabled', false);
        $("#textarea").prop('disabled', false);
    }


</script>