AutoStore/AutoStore/Models/GIOHANG.cs
namespace AutoStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("GIOHANG")]
    public partial class GIOHANG
    {
        [Key]
        [StringLength(10)]
        public string CODE { get; set; }


        [StringLength(10)]
        public string MASP { get; set; }

        
        [StringLength(10)]
        public string MAKH { get; set; }

        public Int32 SOLUONG { get; set; }

        public virtual SANPHAM SANPHAM { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}

AutoStore/AutoStore/Controllers/ClientService/GioHangController.cs
using AutoStore.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace AutoStore.Controllers.ClientService
{
    public class GioHangController : Controller
    {
        private DBConnection db = new DBConnection();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Loaditem()
        {
            string clientuserid = (string)(Session["ClientUserID"]);
            return View(db.GIOHANGs.Include("SANPHAM").Where(a => a.MAKH == clientuserid).ToList());
        }

        public void AddToCart(string idsp)
        {
            string clientuserid = (string)(Session["ClientUserID"]);
            var cartItem = db.GIOHANGs.SingleOrDefault(a => a.MASP == idsp && a.MAKH == clientuserid);
            if (cartItem == null)
            {
                GIOHANG temp = new GIOHANG { CODE = FuncClass.genNextCode(), MAKH = clientuserid, MASP = idsp, SOLUONG = 1 };
                db.GIOHANGs.Add(temp);
            }
            else
            {
                cartItem.SOLUONG = cartItem.SOLUONG + 1;
            }
            // Save changes
            db.SaveChanges();
        }

        public ActionResult cart()
        {
            string clientuserid = (string)(Session["ClientUserID"]);
            return PartialView(db.GIOHANGs.Include("SANPHAM").Where(a => a.MAKH == clientuserid).ToList());
        }

        /// <summary>
        /// delete item in cart
        /// </summary>
        /// <param name="idkh"></param>
        /// <param name="idsp"></param>
        public void delitem(string idkh, string idsp)
        {
            string clientuserid = (string)(Session["ClientUserID"]);
            var temp = db.GIOHANGs.SingleOrDefault(a => a.MASP == idsp && a.MAKH == clientuserid);
            if (temp != null)
            {
                if (temp.SOLUONG == 1)
                {
                    db.GIOHANGs.Remove(temp);
                }
                if (temp.SOLUONG > 1)
                {
                    temp.SOLUONG = temp.SOLUONG - 1;
                }
            }
            db.SaveChanges();
        }

        /// <summary>
        /// delete item in checkout
        /// </summary>
        /// <param name="idkh"></param>
        /// <param name="idsp"></param>
        public void delitem2(string idsp)
        {
            string clientuserid = (string)(Session["ClientUserID"]);
            var temp = db.GIOHANGs.SingleOrDefault(a => a.MASP == idsp && a.MAKH == clientuserid);
            if (temp != null)
            {
                db.GIOHANGs.Remove(temp);
            }
            db.SaveChanges();
        }

        public void decrease(int i, string idsp)
        {
            string clientuserid = (string)(Session["ClientUserID"]);
            var cartItem = db.GIOHANGs.SingleOrDefault(a => a.MASP == idsp && a.MAKH == clientuserid);
            if (cartItem != null)
            {
                cartItem.SOLUONG = i;
                db.SaveChanges();
            }
        }

        public ActionResult Checkout()
        {
            string objmanv = "1211997";
            string objtenpn = "Phiếu xuất hàng " + (string)(Session["ClientUserID"]);
            DateTime objngaynhap = DateTime.Today;
            string objmakh = (string)(Session["ClientUserID"]);
            PHIEUXUAT temp = new PHIEUXUAT { MAPX = FuncClass.genNextCode(), TENPX = objtenpn, MANV = objmanv, NGAYXUAT = objngaynhap, MAKH = objmakh };
            db.PHIEUXUATs.Add(temp);
            db.SaveChanges();
            return View();
        }
    }
}

AutoStore/AutoStore/Views/GioHang/Checkout.cshtml
@{

    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link href="~/Content/ClientVender/css/cartcheckout.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

<section class="b-pageHeader">
    <div class="container">
        <h1 class="wow zoomInLeft" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: zoomInLeft;">Shopping Cart</h1>
        <div class="b-pageHeader__search wow zoomInRight" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: zoomInRight;">
            <h3>Checkout & get the best car you want!</h3>
        </div>
    </div>
</section>

<div class="container" style="margin:150px 20px 150px 700px">
    <h2>Thông tin đã được xác nhận!</h2>
</div>

AutoStore/AutoStore/Views/GioHang/Index.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<link href="~/Content/ClientVender/css/cartcheckout.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

<section class="b-pageHeader">
    <div class="container">
        <h1 class="wow zoomInLeft" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: zoomInLeft;">Shopping Cart</h1>
        <div class="b-pageHeader__search wow zoomInRight" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: zoomInRight;">
            <h3>Checkout & get the best car you want!</h3>
        </div>
    </div>
</section>

<div class="shopping-cart border" style="margin:15px 250px 150px 200px;">

    <div class="column-labels">
        <label class="product-image" style="padding-left:90px">Product</label>
        <label class="product-details" style="padding-left:90px">Description</label>
        <label class="product-price" style="padding-left:30px">Price</label>
        <label class="product-quantity">Quantity</label>
        <label class="product-removal">Remove</label>
        <label class="product-line-price" style="padding-right:30px">Total</label>
    </div>
    <div id="inforcheckout">
        @Html.Action("Loaditem", "GioHang")
    </div>
    

    

    <div class="b-search__main-form-submit">
        <button class="btn m-btn" onclick="location.href='@Url.Action("Checkout", "GioHang")'">Checkout<span class="fa fa-shopping-cart"></span></button>
    </div>
</div>

<script type="text/javascript">
    function decrease(nbid, gia, idsp) {
        var i = $("#NB_" + nbid + "").val();
        if (i > 1) {
            //$('#NB_' + nbid + '').val(i - 1);
            i = i - 1;
            gia = gia * i;
            //$('#gia_' + nbid + '').text(gia);

            $.ajax({
                url: "/GioHang/decrease",
                data: {
                    'i': i,
                    'idsp': idsp
                },
                datatype: 'html',
                type: 'Get',
                success: function () {
                    $.ajax({
                        url: "/GioHang/Loaditem",

                        type: 'Get',
                        success: function (cart) {
                            $("#inforcheckout").html(cart);


                        },
                        error: function () {
                        }
                    });

                },
                error: function () {
                    $("#err_").attr("style", "display:normal");
                }
            });
        }

    }

    function increase(nbid, gia, idsp) {
        var i = $("#NB_" + nbid + "").val();
        if (i > 0) {
            var y = parseInt(i) + 1;
            //$('#NB_' + nbid + '').val(y);

            gia = gia * y;
            //$('#gia_' + nbid + '').text(gia);

            $.ajax({
                url: "/GioHang/decrease",
                data: {
                    'i': y,
                    'idsp': idsp
                },
                datatype: 'html',
                type: 'Get',
                success: function () {
                    $.ajax({
                        url: "/GioHang/Loaditem",

                        type: 'Get',
                        success: function (cart) {
                            $("#inforcheckout").html(cart);


                        },
                        error: function () {
                        }
                    });

                },
                error: function () {
                    $("#err_").attr("style", "display:normal");
                }
            });
        }

    }

    function deleteitem(idsp) {
        $.ajax({
            url: "/GioHang/delitem2",
            data: {
                'idsp': idsp
            },
            datatype: 'html',
            type: 'Get',
            success: function () {
                $.ajax({
                    url: "/GioHang/Loaditem",

                    type: 'Get',
                    success: function (cart) {
                        $("#inforcheckout").html(cart);
                      

                    },
                    error: function () {
                    }
                });

            },
            error: function () {
                $("#err_").attr("style", "display:normal");
            }
        });
    }
</script>
<style>
    input[type="number"]::-webkit-outer-spin-button,
    input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    input[type="number"] {
        -moz-appearance: textfield;
    }
</style>

AutoStore/AutoStore/Views/GioHang/Loaditem.cshtml
@model IEnumerable<AutoStore.Models.GIOHANG>
@{
    Layout =null;
}
@{ Double? cost=0;}
@foreach (var item in Model)
{
    <div class="product">
        <div class="product-image">
            <img src="@item.SANPHAM.HINHANH">
        </div>
        <div class="product-details">
            <div class="product-title"><h5 style="font:700 16px 'Open Sans',sans-serif;">@item.SANPHAM.TENSP</h5></div>
            <p class="product-description"><h5 style="font:100 14px 'Open Sans',sans-serif;margin-right:20px">@item.SANPHAM.MOTA</h5></p>
        </div>
        <div class=" b-featured__item-price" style="width:90px;margin-right:50px">@Html.DisplayFor(Model => item.SANPHAM.DONGIA)</div>
        <div class="product-quantity">
            <button onclick="decrease(@item.MAKH@item.MASP,'@item.SANPHAM.DONGIA','@item.MASP')">-</button>
            <input type="number" id="NB_@item.MAKH@item.MASP" style="width:25px" value="@item.SOLUONG" min="1">
            <button onclick="increase(@item.MAKH@item.MASP,'@item.SANPHAM.DONGIA','@item.MASP')">+</button>
        </div>
        <div class="product-removal" style="margin-left:10px">
            <button class="btn btn-round btn-danger fa fa-trash" style="margin-left:20px" onclick="deleteitem(@item.MASP)"></button>
        </div>
        @{ var temp = item.SOLUONG * item.SANPHAM.DONGIA;
            cost = cost + temp;
            }
        <div class=" b-featured__item-price" style="width:100px;margin-left:70px" id="gia_@item.MAKH@item.MASP">@string.Format("{0:C0}", temp)</div>
    </div>
}
    <div class="totals product">
        <div class="totals-item">
            <label>Subtotal</label>
            <div style="float:right;text-align:right" id="cart-subtotal">@string.Format("{0:C0}", cost)</div>
        </div>
        @{ var temp2 = cost / 5;
        }
        <div class="totals-item">
            <label>Tax x20%</label>
            <div style="float:right;text-align:right" id="cart-shipping">@string.Format("{0:C0}", temp2)</div>
        </div>
        @{ temp2 =cost+ cost / 5;
        }
        <div class="totals-item totals-item-total">
            <label>Grand Total</label>
            <div style="float:right;text-align:right" id="cart-total">@string.Format("{0:C0}", temp2)</div>
        </div>
    </div>

AutoStore/AutoStore/Views/GioHang/cart.cshtml
@model IEnumerable<AutoStore.Models.GIOHANG>

@foreach (var item in Model)
{
    <div class="owl-item col-md-3" style="width: 285px;">
        <div class="b-featured__item">

            <button id="@item.MAKH@item.MASP" class="btn btn-danger" type="reset" style="border-radius: 50%;width:2.5em;height:2.5em;margin-left:180px" onclick="delitem(@item.MAKH,'@item.MASP')">
                <i class="fa fa-close"></i>
            </button>
          
            <a>
                <img src="@item.SANPHAM.HINHANH" alt="@item.SANPHAM.TENSP">
            </a>
            
            <h5><a href="detail.html">@item.SANPHAM.TENSP</a>
            </h5>
            <div class="b-featured__item-price">
                @Html.DisplayFor(modelItem => item.SANPHAM.DONGIA)
            </div>
            <span class="badge" style="margin:10px 0 0 10px">@item.SOLUONG Items</span>
            
        </div>
    </div>
}